@startuml


class "no-basis-Address" as class1
class "no-basis-propertyInformation:extension" as class2
class "no-basis-address-official:extension" as class3
class "no-basisurban-district:extension" as class4
class "no-basis-municipalitycode:extension" as class5

package "FHIR DataTypes" #DDDDDD {
class "Period" as class6
}

class1 *-- class2
class1 *- class6
class1 *-- class3
class1 *-- class4
class1 *-- class5

class1 : use:code[0..1]
class1 : type:code[0..1]
class1 : city:string[0..1]
class1 : district:string[0..1]
class1 : state:string[0..1]
class1 : postalCode:string[0..1]

class2 : cadastralUnitNumber:int[0..1]
class2 : propertyUnitNumber:int[0..1]
class2 : leaseholdNumber:int[0..*]
class2 : condominiumUnitNumber:int[0..*]
class2 : municipality:Coding[0..*]

class3 : valeBoolean:boolean[0..1]

class4 : valueCoding:Coding[0..1]

class5 : valueCoding:Coding[0..1]

@enduml