@startuml
class "no-basis-HumanName" as class1  
class "no-basis-Middlename" as class2
class1 *-- class2 : middlename

class1 : family:string
class1 : given:string[0..*]
class1 : period:Period[0..1]
class1 : prefix:string[0..1]
class1 : suffix:string[0..*]
class1 : text:string[0..1]
class1 : use:code[0..1]

class2 : milddlename:string[0..1]
@enduml