@startmindmap

* Margrethe Johnsen og Johannes Johnsen
** Randi Wiese
*** Randi (f. Johnsen) (1972) og Frithjof Wiese (1921) 
**** Margrethe Johanne (Grete Hanne) Wiese (1920-1994) og Sigurd Müller (?) 
***** Ulf Wiese Müller (1946) og Bente Kristin Müller (1945) 
****** Cathrine Wiese (?)
***** Frithjof Wiese (1947) og Britt Ovidie Remmem Wiese (1962) 
****** Fay B. Narvesen Wiese (1985)
****** Ludvig Wiese (?)
****** Charlotte(?) 
***** Margrethe Solstad (1954) og Trond Ketil Solstad (1947) 
***** Nini Naarstad (1956) og Helge Naarstad (1945) 
****** Carolina Naarstad (1982)
****** Fabian Naarstad (1983)
***** Sigurd Müller(1955) ? (?)
****** Eva Margrethe (?) 
****** Ingerid (?)  
**** Kirsten Wiese Rosenlund (1918-1994) og Johan C. Rosenlund (1911-1989)
***** Randi Christen-sen (1940) og Andreas Møller Christen-sen (1942)
***** Ida Margrethe Knudsen (1942) og Jon Helge Knudsen (1938)
****** Inger Margrethe Knudsen (1972) 
******* Siri Margrethe Graves Knudsen (?)
******* Erik Graves Knudsen (?)
****** Jon Christopher Knudsen (1978) og Cecilie Seim Knudsen (1979)
******* Nathalie Seim Knudsen (?)
******* Aksel Seim Knudsen (?)
***** Jan Christopher Rosenlund (1946) og Eli Tveit Rosenlund (1944) 
****** Thomas Tveit Rosenlund (1974) og Solveig Svantesen (1975)
******* Marie Svantesen Rosenlund (2011)
****** Tone Tveit Rosenlund (1972) og Knut Olav Nyhus Olsen (1972) 
******* Simon Nyhus Rosenlund (2004) 
******* Johanne Nyhus Rosenlund (2004)

@endmindmap