@startmindmap

*:Margrethe Johnsen 
Johannes Johnsen;
**:Randi Wiese (f. Johnsen) (1972) 
Frithjof Wiese (1921);
***:Margrethe Johanne (Grete Hanne) Wiese 
(1920-1994) og Sigurd Müller (?);
****:Ulf Wiese Müller (1946)
Bente Kristin Müller (1945);
***** Cathrine Wiese (?)
****:Frithjof Wiese (1947)
Britt Ovidie Remmem Wiese (1962);
***** Fay B. Narvesen Wiese (1985)
***** Ludvig Wiese (?)
***** Charlotte(?) 
****:Margrethe Solstad (1954)
Trond Ketil Solstad (1947);
****:Nini Naarstad (1956)
Helge Naarstad (1945);
***** Carolina Naarstad (1982)
***** Fabian Naarstad (1983)
**** Sigurd Müller(1955) ? (?)
***** Eva Margrethe (?) 
***** Ingerid (?)  
***:Kirsten Wiese Rosenlund (1918-1994)
Johan C. Rosenlund (1911-1989);
****:Randi Christen-sen (1940)
Andreas Møller Christen-sen (1942);
****:Ida Margrethe Knudsen (1942)
Jon Helge Knudsen (1938);
*****:Inger Margrethe Knudsen (1972)
Jeff Graves (?);
****** Siri Margrethe Graves Knudsen (?)
****** Erik Graves Knudsen (?)
*****:Jon Christopher Knudsen (1978)
Cecilie Seim Knudsen (1979);
****** Nathalie Seim Knudsen (?)
****** Aksel Seim Knudsen (?)
****:Jan Christopher Rosenlund (1946)
Eli Tveit Rosenlund (1944);
*****:Thomas Tveit Rosenlund (1974)
Solveig Svantesen (1975);
****** Marie Svantesen Rosenlund (2011)
*****:Tone Tveit Rosenlund (1972)
Knut Olav Nyhus Olsen (1972);
****** Simon Nyhus Rosenlund (2004) 
****** Johanne Nyhus Rosenlund (2004)

@endmindmap